from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


def generate_alert_history_pdf(alerts_df):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    elements = []

    title = Paragraph(
        "Network Attack Detection System - SOC Alert Report",
        styles["Title"]
    )

    generated_at = Paragraph(
        f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        styles["Normal"]
    )

    elements.append(title)
    elements.append(Spacer(1, 12))
    elements.append(generated_at)
    elements.append(Spacer(1, 20))

    total_alerts = len(alerts_df)
    high_count = len(alerts_df[alerts_df["severity"] == "HIGH"])
    medium_count = len(alerts_df[alerts_df["severity"] == "MEDIUM"])
    low_count = len(alerts_df[alerts_df["severity"] == "LOW"])
    avg_threat = alerts_df["threat_score"].mean()
    max_threat = alerts_df["threat_score"].max()

    elements.append(Paragraph("Executive Summary", styles["Heading2"]))

    summary_text = f"""
    This report summarizes stored IDS alerts generated by the Network Attack Detection System.
    The platform detected and stored {total_alerts} alert records. 
    HIGH severity alerts: {high_count}, MEDIUM severity alerts: {medium_count}, LOW severity alerts: {low_count}.
    Average threat score: {avg_threat:.2f}/100. Maximum threat score: {max_threat:.2f}/100.
    """

    elements.append(Paragraph(summary_text, styles["Normal"]))
    elements.append(Spacer(1, 16))

    elements.append(Paragraph("Alert Metrics", styles["Heading2"]))

    metrics_table_data = [
        ["Metric", "Value"],
        ["Total Alerts", str(total_alerts)],
        ["HIGH Severity", str(high_count)],
        ["MEDIUM Severity", str(medium_count)],
        ["LOW Severity", str(low_count)],
        ["Average Threat Score", f"{avg_threat:.2f}/100"],
        ["Maximum Threat Score", f"{max_threat:.2f}/100"],
    ]

    metrics_table = Table(metrics_table_data, colWidths=[2.8 * inch, 2.8 * inch])
    metrics_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F3F4F6")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    elements.append(metrics_table)
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("Severity Breakdown", styles["Heading2"]))

    severity_counts = alerts_df["severity"].value_counts().reset_index()
    severity_counts.columns = ["Severity", "Count"]

    severity_table_data = [["Severity", "Count"]]
    for _, row in severity_counts.iterrows():
        severity_table_data.append([
            str(row["Severity"]),
            str(row["Count"])
        ])

    severity_table = Table(severity_table_data, colWidths=[2.8 * inch, 2.8 * inch])
    severity_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F2937")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F9FAFB")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    elements.append(severity_table)
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("Top Attack Types", styles["Heading2"]))

    attack_counts = alerts_df["attack_type"].value_counts().head(10).reset_index()
    attack_counts.columns = ["Attack Type", "Count"]

    attack_table_data = [["Attack Type", "Count"]]
    for _, row in attack_counts.iterrows():
        attack_table_data.append([
            str(row["Attack Type"]),
            str(row["Count"])
        ])

    attack_table = Table(attack_table_data, colWidths=[4.0 * inch, 1.6 * inch])
    attack_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F3F4F6")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (1, 1), (-1, -1), "CENTER"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    elements.append(attack_table)
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("Recent Alert Records", styles["Heading2"]))

    recent_df = alerts_df.sort_values(
        by="timestamp",
        ascending=False
    ).head(15)

    recent_table_data = [[
        "Time",
        "Source",
        "Attack",
        "Severity",
        "Threat"
    ]]

    for _, row in recent_df.iterrows():
        recent_table_data.append([
            str(row.get("timestamp", ""))[:19],
            str(row.get("module_source", ""))[:18],
            str(row.get("attack_type", ""))[:22],
            str(row.get("severity", "")),
            f"{float(row.get('threat_score', 0)):.2f}"
        ])

    recent_table = Table(
        recent_table_data,
        colWidths=[
            1.25 * inch,
            1.25 * inch,
            1.65 * inch,
            0.9 * inch,
            0.75 * inch
        ]
    )

    recent_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#7F1D1D")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F9FAFB")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("PADDING", (0, 0), (-1, -1), 5),
    ]))

    elements.append(recent_table)

    doc.build(elements)

    pdf_value = buffer.getvalue()
    buffer.close()

    return pdf_value